/**
 * SEO Data — cities, areas, categories, FAQs, voice queries.
 * This is the single source of truth for all programmatic SEO pages.
 * Admin can extend this via the DB (future); currently static for reliability.
 */

const CITIES = [
  {
    slug: 'hyderabad', name: 'Hyderabad', state: 'Telangana',
    lat: 17.3850, lng: 78.4867, population: '10M+', pinCodes: ['500081', '500032', '500034'],
    description: 'India\'s tech capital with instant on-demand services across all major areas.',
    areas: [
      { slug: 'madhapur',      name: 'Madhapur' },
      { slug: 'gachibowli',    name: 'Gachibowli' },
      { slug: 'kondapur',      name: 'Kondapur' },
      { slug: 'hitech-city',   name: 'HiTech City' },
      { slug: 'jubilee-hills', name: 'Jubilee Hills' },
      { slug: 'banjara-hills', name: 'Banjara Hills' },
      { slug: 'kukatpally',    name: 'Kukatpally' },
      { slug: 'secunderabad',  name: 'Secunderabad' },
      { slug: 'lb-nagar',      name: 'LB Nagar' },
      { slug: 'dilsukhnagar',  name: 'Dilsukhnagar' },
      { slug: 'ameerpet',      name: 'Ameerpet' },
      { slug: 'begumpet',      name: 'Begumpet' },
    ],
  },
  {
    slug: 'bangalore', name: 'Bangalore', state: 'Karnataka',
    lat: 12.9716, lng: 77.5946, population: '13M+', pinCodes: ['560001', '560034', '560103'],
    description: 'Silicon Valley of India — verified professionals available 24/7.',
    areas: [
      { slug: 'koramangala',    name: 'Koramangala' },
      { slug: 'indiranagar',    name: 'Indiranagar' },
      { slug: 'whitefield',     name: 'Whitefield' },
      { slug: 'electronic-city',name: 'Electronic City' },
      { slug: 'jp-nagar',       name: 'JP Nagar' },
      { slug: 'hsr-layout',     name: 'HSR Layout' },
      { slug: 'jayanagar',      name: 'Jayanagar' },
      { slug: 'marathahalli',   name: 'Marathahalli' },
      { slug: 'hebbal',         name: 'Hebbal' },
      { slug: 'yelahanka',      name: 'Yelahanka' },
      { slug: 'rajajinagar',    name: 'Rajajinagar' },
      { slug: 'malleswaram',    name: 'Malleswaram' },
    ],
  },
  {
    slug: 'mumbai', name: 'Mumbai', state: 'Maharashtra',
    lat: 19.0760, lng: 72.8777, population: '20M+', pinCodes: ['400001', '400053', '400076'],
    description: 'The city that never sleeps gets instant services — any time, any area.',
    areas: [
      { slug: 'andheri',    name: 'Andheri' },
      { slug: 'bandra',     name: 'Bandra' },
      { slug: 'powai',      name: 'Powai' },
      { slug: 'thane',      name: 'Thane' },
      { slug: 'borivali',   name: 'Borivali' },
      { slug: 'malad',      name: 'Malad' },
      { slug: 'goregaon',   name: 'Goregaon' },
      { slug: 'kandivali',  name: 'Kandivali' },
      { slug: 'mulund',     name: 'Mulund' },
      { slug: 'ghatkopar',  name: 'Ghatkopar' },
      { slug: 'kurla',      name: 'Kurla' },
      { slug: 'navi-mumbai',name: 'Navi Mumbai' },
    ],
  },
  {
    slug: 'delhi', name: 'Delhi', state: 'Delhi',
    lat: 28.6139, lng: 77.2090, population: '32M+', pinCodes: ['110001', '110045', '110096'],
    description: 'India\'s capital — trusted on-demand professionals across NCR.',
    areas: [
      { slug: 'connaught-place', name: 'Connaught Place' },
      { slug: 'south-delhi',     name: 'South Delhi' },
      { slug: 'dwarka',          name: 'Dwarka' },
      { slug: 'rohini',          name: 'Rohini' },
      { slug: 'lajpat-nagar',    name: 'Lajpat Nagar' },
      { slug: 'saket',           name: 'Saket' },
      { slug: 'janakpuri',       name: 'Janakpuri' },
      { slug: 'preet-vihar',     name: 'Preet Vihar' },
      { slug: 'noida',           name: 'Noida' },
      { slug: 'gurugram',        name: 'Gurugram' },
      { slug: 'faridabad',       name: 'Faridabad' },
      { slug: 'ghaziabad',       name: 'Ghaziabad' },
    ],
  },
  {
    slug: 'chennai', name: 'Chennai', state: 'Tamil Nadu',
    lat: 13.0827, lng: 80.2707, population: '11M+', pinCodes: ['600001', '600020', '600096'],
    description: 'The Detroit of India — fast, reliable home and vehicle services.',
    areas: [
      { slug: 'anna-nagar',    name: 'Anna Nagar' },
      { slug: 't-nagar',       name: 'T Nagar' },
      { slug: 'adyar',         name: 'Adyar' },
      { slug: 'velachery',     name: 'Velachery' },
      { slug: 'tambaram',      name: 'Tambaram' },
      { slug: 'perambur',      name: 'Perambur' },
      { slug: 'omr',           name: 'OMR' },
      { slug: 'sholinganallur',name: 'Sholinganallur' },
      { slug: 'guindy',        name: 'Guindy' },
      { slug: 'porur',         name: 'Porur' },
      { slug: 'chromepet',     name: 'Chromepet' },
      { slug: 'ambattur',      name: 'Ambattur' },
    ],
  },
  {
    slug: 'pune', name: 'Pune', state: 'Maharashtra',
    lat: 18.5204, lng: 73.8567, population: '7M+', pinCodes: ['411001', '411014', '411045'],
    description: 'The Oxford of the East — smart city with instant professional services.',
    areas: [
      { slug: 'koregaon-park',  name: 'Koregaon Park' },
      { slug: 'baner',          name: 'Baner' },
      { slug: 'hinjewadi',      name: 'Hinjewadi' },
      { slug: 'wakad',          name: 'Wakad' },
      { slug: 'kothrud',        name: 'Kothrud' },
      { slug: 'hadapsar',       name: 'Hadapsar' },
      { slug: 'viman-nagar',    name: 'Viman Nagar' },
      { slug: 'kalyani-nagar',  name: 'Kalyani Nagar' },
      { slug: 'aundh',          name: 'Aundh' },
      { slug: 'magarpatta',     name: 'Magarpatta' },
      { slug: 'kondhwa',        name: 'Kondhwa' },
      { slug: 'pimpri',         name: 'Pimpri' },
    ],
  },
];

const CATEGORIES = [
  {
    slug: 'mobile-repair',
    name: 'Mobile Repair',
    plural: 'Mobile Repair Services',
    icon: '📱',
    spaPath: '/book?service=mobile_repair',
    searchTerms: ['mobile repair near me', 'phone repair', 'screen repair', 'mobile service center', 'smartphone repair'],
    voiceQuery: 'Who can repair my phone near me?',
    h1Template: (loc) => `Mobile Repair in ${loc} — Doorstep Service`,
    descTemplate: (loc) => `Cracked screen? Battery issues? Get certified mobile repair technicians at your doorstep in ${loc}. All brands. Same-day service. Warranty on repairs.`,
    features: ['All Brands Covered', 'Screen Replacement', 'Battery Replacement', 'Water Damage Repair', 'Software Issues', '30-Day Warranty'],
    avgTime: '30–60 min',
    startingPrice: '₹199',
    faqs: [
      { q: 'How quickly can a mobile repair technician arrive?', a: 'Zappy connects you with verified mobile repair technicians in under 15 minutes. Average arrival time is 20–30 minutes in most areas.' },
      { q: 'Do you repair all mobile phone brands?', a: 'Yes. Our technicians service all major brands including Samsung, Apple, Xiaomi, OnePlus, Oppo, Vivo, Realme, and all other Android and iOS devices.' },
      { q: 'Is there a warranty on mobile repairs?', a: 'Yes. All repairs come with a 30-day warranty. If the same issue recurs within 30 days, we fix it free of charge.' },
      { q: 'What is the cost of mobile screen replacement?', a: 'Screen replacement starts from ₹699 and varies by model. You get an exact price quote before the technician begins work — no hidden charges.' },
      { q: 'Can I get my phone repaired at home?', a: 'Absolutely. Zappy offers doorstep mobile repair across all major areas. Book online and a technician comes to you — home, office, or anywhere.' },
    ],
    howTo: {
      name: 'How to Book Mobile Repair with Zappy',
      steps: [
        { name: 'Describe the Problem', text: 'Open Zappy and describe your phone issue — cracked screen, battery drain, charging port, etc.' },
        { name: 'Get an Instant Quote', text: 'Receive a transparent price quote upfront. No hidden charges, no surprises.' },
        { name: 'Technician Arrives', text: 'A verified technician reaches your location in 20–30 minutes with all parts and tools.' },
        { name: 'Repair Done', text: 'Your phone is repaired on-site. Test it before paying. 30-day warranty included.' },
      ],
    },
  },
  {
    slug: 'bike-puncture',
    name: 'Bike Puncture Repair',
    plural: 'Bike Puncture Services',
    icon: '🏍️',
    spaPath: '/book?service=bike_puncture',
    searchTerms: ['bike puncture near me', 'two wheeler puncture', 'tyre repair near me', 'motorcycle puncture', 'scooter tyre repair'],
    voiceQuery: 'Who can fix my bike puncture near me?',
    h1Template: (loc) => `Bike Puncture Repair in ${loc} — Roadside Assistance`,
    descTemplate: (loc) => `Stuck with a flat tyre in ${loc}? Zappy sends a puncture repair mechanic to your exact location in minutes. Two-wheelers, scooters, motorcycles — all covered.`,
    features: ['Doorstep Service', 'All Two-Wheelers', 'Tubeless & Tube Tyres', 'Emergency Roadside', 'Cash & Online Payment', 'Instant Response'],
    avgTime: '15–30 min',
    startingPrice: '₹149',
    faqs: [
      { q: 'How fast can you fix a bike puncture near me?', a: 'Zappy dispatches a mechanic immediately. Average response time is 15–20 minutes. For roadside emergencies, we prioritize your request.' },
      { q: 'Do you repair both tube and tubeless tyres?', a: 'Yes. We repair both tube-type and tubeless tyres for all two-wheelers including scooters, motorcycles, and mopeds.' },
      { q: 'What is the cost of bike puncture repair?', a: 'Bike puncture repair starts from ₹149. Tubeless tyre repair may cost slightly more. You get a quote before the mechanic starts work.' },
      { q: 'Do you provide roadside assistance?', a: 'Yes. Zappy offers roadside puncture repair. Share your live location and our mechanic reaches you wherever you are.' },
      { q: 'Can you replace a tyre if it cannot be repaired?', a: 'Yes. If the puncture cannot be patched, the mechanic can replace the inner tube or arrange a new tyre at competitive prices.' },
    ],
    howTo: {
      name: 'How to Get Bike Puncture Repair with Zappy',
      steps: [
        { name: 'Share Your Location', text: 'Open Zappy and share your current location — roadside or at home.' },
        { name: 'Instant Dispatch', text: 'The nearest verified mechanic is dispatched immediately to your location.' },
        { name: 'Repair On-Site', text: 'The mechanic repairs your puncture on the spot with all necessary tools.' },
        { name: 'Pay & Ride', text: 'Pay securely via Zappy. Cash and online both accepted. Get back on the road.' },
      ],
    },
  },
  {
    slug: 'laptop-repair',
    name: 'Laptop Repair',
    plural: 'Laptop Repair Services',
    icon: '💻',
    spaPath: '/book?service=laptop_repair',
    searchTerms: ['laptop repair near me', 'computer repair', 'laptop service center', 'laptop not working', 'laptop screen repair'],
    voiceQuery: 'Who can fix my laptop near me?',
    h1Template: (loc) => `Laptop Repair in ${loc} — Certified Technicians`,
    descTemplate: (loc) => `Laptop not starting? Slow performance? Get certified laptop repair at your doorstep in ${loc}. All brands. Virus removal, screen replacement, RAM upgrade — all covered.`,
    features: ['All Laptop Brands', 'Screen Replacement', 'Virus Removal', 'Hardware Upgrades', 'Data Recovery', '60-Day Warranty'],
    avgTime: '1–3 hours',
    startingPrice: '₹299',
    faqs: [
      { q: 'Do you repair all laptop brands?', a: 'Yes. Zappy technicians repair all laptop brands including Dell, HP, Lenovo, Apple MacBook, Asus, Acer, Samsung, and more.' },
      { q: 'How long does laptop repair take?', a: 'Most common repairs like screen replacement, RAM upgrade, and virus removal are done within 1–3 hours on-site. Complex repairs may take longer.' },
      { q: 'Can you recover data from a damaged laptop?', a: 'Yes. Our technicians provide data recovery services. We\'ll attempt to recover your data before any repair that might affect storage.' },
      { q: 'What does laptop repair cost?', a: 'Laptop repair starts from ₹299 for diagnostics. You get a detailed quote after the initial check — no work begins without your approval.' },
      { q: 'Do you repair MacBooks?', a: 'Yes. We have Apple MacBook certified technicians who can handle screen replacements, battery replacements, keyboard issues, and software problems.' },
    ],
    howTo: {
      name: 'How to Book Laptop Repair with Zappy',
      steps: [
        { name: 'Describe the Issue', text: 'Tell us what\'s wrong — slow laptop, broken screen, won\'t start, virus, etc.' },
        { name: 'Get a Quote', text: 'Receive a transparent estimate. Approve before any work begins.' },
        { name: 'Technician at Your Door', text: 'A certified technician arrives at your location with tools and parts.' },
        { name: 'Repair & Warranty', text: 'Laptop repaired on-site. 60-day warranty on all repairs.' },
      ],
    },
  },
  {
    slug: 'birthday-decoration',
    name: 'Birthday Decoration',
    plural: 'Birthday Decoration Services',
    icon: '🎂',
    spaPath: '/events',
    searchTerms: ['birthday decoration near me', 'birthday party decoration', 'room decoration for birthday', 'balloon decoration', 'surprise decoration'],
    voiceQuery: 'Who can do birthday decorations near me today?',
    h1Template: (loc) => `Birthday Decoration in ${loc} — Same-Day Setup`,
    descTemplate: (loc) => `Make birthdays unforgettable in ${loc}. Professional birthday decorators create magical themes — balloon bouquets, backdrops, fairy lights, and more. Book online, we set up at your venue.`,
    features: ['Theme-Based Décor', 'Balloon Arrangements', 'LED & Fairy Lights', 'Photo Booth Setup', 'Cake Table Décor', 'Same-Day Booking'],
    avgTime: '2–4 hours setup',
    startingPrice: '₹1,499',
    faqs: [
      { q: 'Can I book birthday decoration for the same day?', a: 'Yes. Zappy accepts same-day birthday decoration bookings subject to availability. Book at least 2 hours in advance for same-day service.' },
      { q: 'What themes are available for birthday decoration?', a: 'We offer themes including Unicorn, Superhero, Princess, Balloon Fiesta, Floral, Fairy Lights, and more. Custom themes are also available.' },
      { q: 'What does birthday decoration cost?', a: 'Birthday decoration starts from ₹1,499. Package prices vary based on theme, balloon count, and add-ons. Full pricing shown before booking.' },
      { q: 'Do you provide decorations at home, hotels, and halls?', a: 'Yes. Zappy decorators set up at homes, hotel rooms, banquet halls, restaurants, and outdoor venues.' },
      { q: 'Is 30% advance payment required for event booking?', a: 'Yes. A 30% advance payment is collected to confirm your slot. The remaining 70% is collected on the event day after the setup is complete.' },
    ],
    howTo: {
      name: 'How to Book Birthday Decoration with Zappy',
      steps: [
        { name: 'Choose Your Theme', text: 'Browse decoration themes and pick your favourite or request a custom design.' },
        { name: 'Select Date & Time', text: 'Pick your event date, time slot, and share the venue address.' },
        { name: 'Pay 30% Advance', text: 'Confirm your booking with a small 30% advance. Balance paid on the day.' },
        { name: 'We Set Up Everything', text: 'Our professional decorator arrives and transforms your venue.' },
      ],
    },
  },
  {
    slug: 'electrician',
    name: 'Electrician',
    plural: 'Electrician Services',
    icon: '⚡',
    spaPath: '/book?service=electrician',
    searchTerms: ['electrician near me', 'electrical repair near me', 'electrician for home', 'wiring repair', 'fan installation near me'],
    voiceQuery: 'Can I get an electrician near me right now?',
    h1Template: (loc) => `Electrician in ${loc} — Same-Day Home Service`,
    descTemplate: (loc) => `Power cut? Fan not working? Get a verified electrician at your home in ${loc} within 30 minutes. Wiring, switches, fans, AC, inverter — all electrical work covered.`,
    features: ['Licensed Electricians', 'Wiring & Rewiring', 'Fan & Light Installation', 'Switch Board Repair', 'AC & Geyser Wiring', 'Emergency Service'],
    avgTime: '30–90 min',
    startingPrice: '₹199',
    faqs: [
      { q: 'How quickly can an electrician reach my home?', a: 'Zappy dispatches a verified electrician within 15 minutes of booking. Average arrival time is 25–35 minutes.' },
      { q: 'Do your electricians handle both minor and major electrical work?', a: 'Yes. From replacing a fuse to complete home rewiring, our certified electricians handle all types of electrical work safely.' },
      { q: 'Is electrical work covered under warranty?', a: 'Yes. All electrical work done by Zappy technicians carries a 30-day service warranty.' },
      { q: 'Do you provide emergency electrician services?', a: 'Yes. Zappy\'s emergency service is available 24/7. Mark your booking as urgent for priority dispatch.' },
      { q: 'What is the minimum charge for an electrician visit?', a: 'Electrician service starts from ₹199 for a visit and basic inspection. Additional charges apply based on work done.' },
    ],
    howTo: {
      name: 'How to Book an Electrician with Zappy',
      steps: [
        { name: 'Describe the Electrical Issue', text: 'Tell us what needs fixing — power failure, fan, wiring, switch board, etc.' },
        { name: 'Instant Dispatch', text: 'A verified electrician near you is dispatched immediately.' },
        { name: 'Safe Repair at Home', text: 'The electrician arrives with tools and fixes the issue safely and efficiently.' },
        { name: 'Pay After Work', text: 'Review the completed work and pay securely through Zappy.' },
      ],
    },
  },
  {
    slug: 'plumber',
    name: 'Plumber',
    plural: 'Plumbing Services',
    icon: '🔧',
    spaPath: '/book?service=plumber',
    searchTerms: ['plumber near me', 'plumbing repair near me', 'pipe leak repair', 'drain cleaning', 'tap repair near me'],
    voiceQuery: 'Can I get a plumber near me right now?',
    h1Template: (loc) => `Plumber in ${loc} — Emergency & Scheduled Service`,
    descTemplate: (loc) => `Leaking pipe? Blocked drain? Get a certified plumber at your home in ${loc} within 30 minutes. All plumbing repairs, installation, and maintenance covered.`,
    features: ['Emergency Plumbing', 'Pipe Leak Repair', 'Drain Unblocking', 'Tap & Faucet Repair', 'Geyser Installation', 'Bathroom Fitting'],
    avgTime: '30–120 min',
    startingPrice: '₹199',
    faqs: [
      { q: 'How fast can a plumber reach my home?', a: 'Zappy dispatches the nearest verified plumber to your location. Average arrival time is 25–35 minutes.' },
      { q: 'Do you handle emergency plumbing like burst pipes?', a: 'Yes. Zappy has emergency plumbing available 24/7. For urgent issues like burst pipes or major leaks, mark your booking as emergency.' },
      { q: 'What plumbing services do you offer?', a: 'We cover pipe repair, tap replacement, drainage cleaning, bathroom fitting, geyser installation, toilet repair, and complete plumbing maintenance.' },
      { q: 'Is there a warranty on plumbing work?', a: 'Yes. All plumbing work comes with a 30-day service warranty. If the same issue returns, we fix it at no charge.' },
      { q: 'What is the cost of a plumber visit?', a: 'Plumbing services start from ₹199 for a visit and inspection. You get a detailed quote before any repair work begins.' },
    ],
    howTo: {
      name: 'How to Book a Plumber with Zappy',
      steps: [
        { name: 'Describe the Issue', text: 'Tell us about the plumbing problem — leaking pipe, blocked drain, broken tap, etc.' },
        { name: 'Instant Dispatch', text: 'The nearest certified plumber is dispatched to your location immediately.' },
        { name: 'Professional Repair', text: 'The plumber arrives with tools and materials and fixes the issue efficiently.' },
        { name: 'Pay Securely', text: 'Approve the work and pay through Zappy. 30-day warranty on all work.' },
      ],
    },
  },
];

const CITY_MAP = Object.fromEntries(CITIES.map(c => [c.slug, c]));
const CATEGORY_MAP = Object.fromEntries(CATEGORIES.map(c => [c.slug, c]));

// Speakable content blocks for Google Assistant / voice search
const BRAND_SPEAKABLE = {
  name: 'Zappy',
  tagline: 'Instant help from verified professionals. Available 24/7.',
  description: 'Zappy is India\'s fastest on-demand service platform. Book plumbers, electricians, mobile repair technicians, bike mechanics, and birthday decorators instantly. Professionals reach you in under 30 minutes.',
};

module.exports = { CITIES, CATEGORIES, CITY_MAP, CATEGORY_MAP, BRAND_SPEAKABLE };
