/**
 * Fallback "from" prices (₹, rupees) per service code.
 *
 * The live Service Catalog (`useListServicesQuery`) is ALWAYS the source of
 * truth and is preferred whenever it's loaded. This map only kicks in when the
 * catalog hasn't resolved yet (or a request failed), so home-page cards show a
 * real price instead of a bare "Get Quote". Snapshot of catalog minimums —
 * regenerate if catalog floors change.
 */
export const SERVICE_PRICE_FALLBACK = {
  auto_repair: 499,
  battery_jump_start: 299,
  battery_replacement: 799,
  bike_battery_issue: 399,
  bike_brake_issue: 249,
  bike_breakdown: 299,
  bike_chain_issue: 199,
  bike_service: 399,
  bike_wash: 199,
  bill_payment_assist: 79,
  camera_issue: 699,
  car_breakdown: 499,
  car_detailing: 1499,
  car_puncture: 199,
  car_service: 1499,
  car_wash: 299,
  cctv_install: 1499,
  cctv_repair: 799,
  charging_issue: 499,
  commercial_emergency: 999,
  commercial_scheduled_maintenance: 999,
  data_recovery: 999,
  device_not_turning_on: 499,
  document_submission: 149,
  elder_companion: 499,
  elder_doctor_visit: 599,
  elder_home_visit: 399,
  elder_transport: 499,
  event_birthday_setup: 1000,
  event_catering_assist: 800,
  event_cleaning_crew: 799,
  event_decorator: 1499,
  event_helper: 599,
  event_lighting_crew: 1499,
  event_photography_assist: 800,
  event_security_crew: 800,
  event_setup_crew: 999,
  event_sound_crew: 1499,
  event_wedding_setup: 3000,
  fleet_support: 1499,
  fuel_delivery: 99,
  grocery_assistance: 149,
  home_automation_setup: 2499,
  home_visit_check: 399,
  hospital_companion: 499,
  laptop_charging_issue: 499,
  laptop_data_recovery: 999,
  laptop_keyboard_issue: 599,
  laptop_motherboard_issue: 1499,
  laptop_ram_upgrade: 499,
  laptop_screen_issue: 1499,
  laptop_slow: 499,
  laptop_ssd_upgrade: 599,
  laptop_virus_removal: 499,
  medicine_pickup: 149,
  microphone_issue: 499,
  minor_roadside_repair: 300,
  pet_grooming: 400,
  pet_sitting: 250,
  pet_training_assist: 600,
  pet_transport: 300,
  pet_vet_assist: 500,
  pet_walking: 150,
  puncture: 149,
  router_setup: 399,
  router_troubleshoot: 399,
  screen_replacement: 999,
  smart_lock_install: 1499,
  smart_tv_install: 599,
  smart_tv_repair: 999,
  software_issue: 399,
  speaker_mic_issue: 499,
  van_repair: 599,
  water_damage: 599,
  water_damage_check: 500,
};

export default SERVICE_PRICE_FALLBACK;
