/**
 * Phone Component Health Report
 * Generated by worker after any phone repair.
 * Tests each component and records pass/fail/score.
 * Customer gets a digital health certificate — "Your iPhone 14: 88% healthy"
 *
 * No Indian mobile repair service generates post-repair health certificates.
 * This is what Apple Authorised Service Providers do. We make it accessible.
 */
const mongoose = require('mongoose');

const phoneHealthSchema = new mongoose.Schema({
  orderId:   { type: mongoose.Schema.Types.ObjectId, ref: 'Order', required: true, unique: true },
  workerId:  { type: mongoose.Schema.Types.ObjectId, ref: 'Worker', required: true },
  userId:    { type: mongoose.Schema.Types.ObjectId, ref: 'User',  required: true, index: true },

  /* Device info */
  deviceBrand:  String,
  deviceModel:  String,
  deviceSeries: String,

  /* Component tests — worker marks each */
  components: {
    screen: {
      status:  { type: String, enum: ['pass', 'fail', 'not_tested'], default: 'not_tested' },
      notes:   String,
      /* Touch zones tested: full screen mapping */
      touchOk: { type: Boolean, default: null },
      colorsOk:{ type: Boolean, default: null },
    },
    battery: {
      status:      { type: String, enum: ['pass', 'fail', 'not_tested'], default: 'not_tested' },
      healthPct:   Number,   // e.g. 87 = 87% capacity
      cycleCount:  Number,   // if readable
      chargesOk:   Boolean,
      notes:       String,
    },
    camera: {
      status:    { type: String, enum: ['pass', 'fail', 'not_tested'], default: 'not_tested' },
      frontOk:   Boolean,
      rearOk:    Boolean,
      flashOk:   Boolean,
      notes:     String,
    },
    audio: {
      status:    { type: String, enum: ['pass', 'fail', 'not_tested'], default: 'not_tested' },
      speakerOk: Boolean,
      micOk:     Boolean,
      earphoneOk:Boolean,
      notes:     String,
    },
    connectivity: {
      status:    { type: String, enum: ['pass', 'fail', 'not_tested'], default: 'not_tested' },
      wifiOk:    Boolean,
      bluetoothOk: Boolean,
      simOk:     Boolean,
      notes:     String,
    },
    charging: {
      status:    { type: String, enum: ['pass', 'fail', 'not_tested'], default: 'not_tested' },
      portOk:    Boolean,
      chargesAt: String,  // e.g. "20W"
      notes:     String,
    },
    buttons: {
      status:    { type: String, enum: ['pass', 'fail', 'not_tested'], default: 'not_tested' },
      powerOk:   Boolean,
      volumeOk:  Boolean,
      fingerprintOk: Boolean,
      notes:     String,
    },
  },

  /* Overall score 0–100 */
  overallScore:   { type: Number, min: 0, max: 100 },
  grade:          { type: String, enum: ['A+', 'A', 'B+', 'B', 'C', 'D'] },
  summary:        String,

  /* Parts used in this repair */
  partsReplaced: [{
    name:          String,
    brand:         String,
    tier:          { type: String, enum: ['OEM', 'Compatible', 'Budget'] },
    warrantyDays:  Number,
  }],

  /* Certificate ID (shown on the card) */
  certificateId: { type: String, unique: true, sparse: true },

  generatedAt: { type: Date, default: Date.now },
}, { timestamps: true });

/* Compute grade from score */
phoneHealthSchema.statics.gradeFromScore = function(score) {
  if (score >= 92) return 'A+';
  if (score >= 83) return 'A';
  if (score >= 74) return 'B+';
  if (score >= 65) return 'B';
  if (score >= 50) return 'C';
  return 'D';
};

module.exports = mongoose.model('PhoneHealthReport', phoneHealthSchema);
