/**
 * Vehicle Health Reports
 * Covers both:
 *   A) Tyre Health Assessment — per tyre: tread depth, sidewall, pressure
 *   B) Battery Health Diagnostic — CCA test, voltage, load test, life estimate
 *
 * Both are generated by worker during/after service.
 * Customer gets professional report instead of verbal "your battery is low."
 * Zero Indian roadside/vehicle service companies do this digitally.
 */
const mongoose = require('mongoose');

/* Tyre report: one entry per tyre */
const tyreCheckSchema = new mongoose.Schema({
  position:      { type: String, enum: ['front_left', 'front_right', 'rear_left', 'rear_right', 'spare'], required: true },
  treadDepthMm:  Number,  // legal minimum in India: 1.6mm; safe: >3mm
  pressurePsi:   Number,
  sidewallOk:    Boolean,
  hasNail:       Boolean,
  repaired:      Boolean,
  recommendReplacement: Boolean,
  notes:         String,
}, { _id: false });

/* Battery diagnostic */
const batteryDiagSchema = new mongoose.Schema({
  voltageV:      Number,   // resting voltage: 12.6V = fully charged; <11.8V = dead
  ccaRating:     Number,   // Cold Cranking Amps (should match spec on label)
  ccaTested:     Number,   // actual measured CCA
  loadTestPass:  Boolean,  // voltage holds under load
  chargingV:     Number,   // alternator output (should be 13.8–14.8V)
  estimatedLifeMonths: Number,
  recommendation: { type: String, enum: ['good', 'charge_only', 'replace_soon', 'replace_now'] },
  notes:         String,
}, { _id: false });

const vehicleHealthReportSchema = new mongoose.Schema({
  orderId:        { type: mongoose.Schema.Types.ObjectId, ref: 'Order', required: true, unique: true },
  workerId:       { type: mongoose.Schema.Types.ObjectId, ref: 'Worker', required: true },
  userId:         { type: mongoose.Schema.Types.ObjectId, ref: 'User',  required: true, index: true },
  vehicleProfileId: { type: mongoose.Schema.Types.ObjectId, ref: 'VehicleProfile', default: null },

  vehicleType:    String,
  registrationNo: String,
  make:           String,
  model:          String,

  /* Report sections */
  tyres:          [tyreCheckSchema],
  battery:        batteryDiagSchema,

  /* Summary */
  overallCondition: { type: String, enum: ['excellent', 'good', 'needs_attention', 'urgent'], default: 'good' },
  technicalNotes:   String,

  /* Pre-service damage documentation photos (for wash/repair) */
  preDamageDocs: [{
    area:     { type: String, enum: ['front', 'rear', 'left', 'right', 'top', 'interior', 'engine', 'other'] },
    photoUrl: String,
    notes:    String,
  }],

  reportType:   { type: String, enum: ['tyre', 'battery', 'full', 'pre_damage'], required: true },
  generatedAt:  { type: Date, default: Date.now },
}, { timestamps: true });

vehicleHealthReportSchema.index({ userId: 1, reportType: 1 });

module.exports = mongoose.model('VehicleHealthReport', vehicleHealthReportSchema);
