/**
 * Cashfree Payment Gateway client.
 * Docs: https://docs.cashfree.com/reference/pg-new-apis-endpoint
 *
 * Key differences from Razorpay:
 *  - Auth: x-client-id + x-client-secret headers (not Basic)
 *  - Amounts are in RUPEES (not paise) — we convert internally
 *  - Order IDs are set BY US (string), not generated by Cashfree
 *  - Webhook HMAC uses: base64(HMAC-SHA256(timestamp + rawBody, secret))
 *  - No checkout signature verification — frontend posts cfPaymentId;
 *    backend confirms by fetching payment status from API
 */

const crypto = require('crypto');
const config = require('../../config');
const logger = require('../../utils/logger');

const BASE_URL = config.cashfree.env === 'production'
  ? 'https://api.cashfree.com/pg'
  : 'https://sandbox.cashfree.com/pg';

const API_VERSION = '2023-08-01';

async function cfRequest(method, path, body) {
  const res = await fetch(`${BASE_URL}${path}`, {
    method,
    headers: {
      'x-client-id':     config.cashfree.appId,
      'x-client-secret': config.cashfree.secretKey,
      'x-api-version':   API_VERSION,
      'Content-Type':    'application/json',
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    logger.error({ status: res.status, data, path }, 'Cashfree API error');
    throw Object.assign(new Error(data?.message || 'Cashfree API error'), {
      status: 502, code: 'CASHFREE_API_ERROR', details: data,
    });
  }
  return data;
}

/**
 * Create a Cashfree order.
 * Returns { cf_order_id, order_id, payment_session_id, order_status }.
 * The frontend uses payment_session_id to launch the Cashfree Drop.
 *
 * @param {object} p
 * @param {string} p.orderId         Our own order ID (e.g. "zappy_ord_abc123")
 * @param {number} p.amountPaise     Amount in paise — converted to rupees internally
 * @param {object} p.customer        { id, phone, email, name }
 * @param {object} [p.tags]          Key-value tags stored on the Cashfree order
 * @param {string} [p.notifyUrl]     Webhook URL for this order
 */
async function createOrder({ orderId, amountPaise, customer, tags = {}, notifyUrl }) {
  const amountRupees = +(amountPaise / 100).toFixed(2);
  return cfRequest('POST', '/orders', {
    order_id:       orderId,
    order_amount:   amountRupees,
    order_currency: 'INR',
    customer_details: {
      customer_id:    String(customer.id),
      customer_phone: customer.phone || '9999999999',
      customer_email: customer.email || 'noreply@zappy.in',
      customer_name:  customer.name  || undefined,
    },
    order_meta: {
      notify_url: notifyUrl || process.env.CASHFREE_WEBHOOK_URL || undefined,
      payment_methods: 'upi,cc,dc,nb,wallet,emi',
    },
    order_tags: tags,
  });
}

/**
 * Fetch all payments for an order.
 * Used to confirm payment status after frontend notifies us.
 */
async function getOrderPayments(orderId) {
  return cfRequest('GET', `/orders/${encodeURIComponent(orderId)}/payments`);
}

/**
 * Fetch a specific payment by cfPaymentId.
 */
async function getPayment(cfPaymentId) {
  return cfRequest('GET', `/payments/${encodeURIComponent(cfPaymentId)}`);
}

/**
 * Issue a refund for an order.
 *
 * @param {string} orderId     Our Cashfree order ID
 * @param {number} amountPaise Refund amount in paise
 * @param {string} refundId    Unique refund ID (idempotency key)
 */
async function createRefund({ orderId, amountPaise, refundId, note = 'Admin refund' }) {
  const amountRupees = +(amountPaise / 100).toFixed(2);
  return cfRequest('POST', `/orders/${encodeURIComponent(orderId)}/refunds`, {
    refund_amount: amountRupees,
    refund_id:     refundId,
    refund_note:   note,
  });
}

/**
 * Verify a Cashfree webhook signature.
 *
 *   x-webhook-timestamp: Unix timestamp (seconds)
 *   x-webhook-signature: base64(HMAC-SHA256(timestamp + rawBody, clientSecret))
 *
 * IMPORTANT: rawBody must be the unparsed Buffer/string — do NOT parse then re-stringify.
 */
function verifyWebhookSignature(rawBody, timestamp, signature) {
  if (!signature || !timestamp) return false;
  const message  = timestamp + rawBody.toString('utf8');
  const expected = crypto
    .createHmac('sha256', config.cashfree.secretKey)
    .update(message)
    .digest('base64');
  // Constant-time compare
  try {
    return crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(signature));
  } catch {
    return false;
  }
}

module.exports = {
  createOrder,
  getOrderPayments,
  getPayment,
  createRefund,
  verifyWebhookSignature,
};
